[versions]

dataframe = "0.15.0"
exposed = "0.60.0"

[libraries]
attributes = "space.kscience:attributes-kt:0.3.0"
kotlinx-dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "dataframe" }
csv = "com.jsoizo:kotlin-csv:1.10.0"
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }

[plugins]