name: Dokka publication

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.7.0
        with:
          java-version: 21
          distribution: liberica
      - name: Cache konan
        uses: actions/cache@v4.2.1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: dokkaGenerateModuleHtml --no-parallel
      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build/dokka-module/html
